# Generated by Django 5.2.8 on 2026-03-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False,
                                                     help_text='Designates that this user has all permissions without explicitly assigning them.',
                                                     verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='工号')),
                ('real_name', models.CharField(max_length=100, verbose_name='真实姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话号码')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部门')),
                ('is_staff', models.BooleanField(default=False, help_text='指明用户是否可以登录到管理站点。',
                                                 verbose_name='职员状态')),
                ('is_active',
                 models.BooleanField(default=True, help_text='指明用户是否被认为是活跃的。以非活跃用户身份登录应被禁止。',
                                     verbose_name='激活状态')),
                ('groups', models.ManyToManyField(blank=True,
                                                  help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                                                  related_name='user_set', related_query_name='user', to='auth.group',
                                                  verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.',
                                                            related_name='user_set', related_query_name='user',
                                                            to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户管理',
                'db_table': 'auth_user',
            },
        ),
    ]
