# Generated by Django 5.2.8 on 2026-04-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_network_engineer',
            field=models.BooleanField(default=False, help_text='指明用户是否为网络工程师角色。',
                                      verbose_name='网络工程师'),
        ),
    ]
