# Generated by Django 5.2.8 on 2026-03-13 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('sex', models.CharField(default='男', max_length=1, verbose_name='性别，默认男')),
                ('phone1', models.CharField(max_length=11, validators=[
                    django.core.validators.RegexValidator(message='请输入11位数字的手机号码', regex='^\\d{11}$')],
                                            verbose_name='电话1')),
                ('phone2', models.CharField(max_length=11, null=True, validators=[
                    django.core.validators.RegexValidator(message='请输入11位数字的手机号码', regex='^\\d{11}$')],
                                            verbose_name='电话2')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('company', models.CharField(max_length=100, null=True, verbose_name='公司')),
                ('position', models.CharField(max_length=100, null=True, verbose_name='职务')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='地址')),
                ('remarks', models.TextField(null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
                'ordering': ['name'],
            },
        ),
    ]
