# Generated by Django 5.2.8 on 2026-03-13 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone1',
            field=models.CharField(max_length=11, validators=[
                django.core.validators.RegexValidator(message='请输入有效的电话号码', regex='^[\\d\\-\\*\\s]+$')],
                                   verbose_name='电话1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone2',
            field=models.CharField(max_length=11, null=True, validators=[
                django.core.validators.RegexValidator(message='请输入有效的电话号码', regex='^[\\d\\-\\*\\s]+$')],
                                   verbose_name='电话2'),
        ),
    ]
