# Generated by Django 5.2.8 on 2026-03-13 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('contact', '0002_alter_contact_phone1_alter_contact_phone2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone1',
            field=models.CharField(max_length=20, validators=[
                django.core.validators.RegexValidator(message='请输入有效的电话号码', regex='^[\\d\\-\\*\\s]+$')],
                                   verbose_name='电话 1'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[
                django.core.validators.RegexValidator(message='请输入有效的电话号码', regex='^[\\d\\-\\*\\s]+$')],
                                   verbose_name='电话 2'),
        ),
    ]
