"""
Django settings for setting project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5iu5jbk^ql_^pvst*jkgr_cr-6&ef71v(e744fc+(r=@o8hqbe'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '127.0.0.1',  # 本地回环地址
    'localhost',  # 本地主机名
]
# Application definition

INSTALLED_APPS = [
    'simpleui',  # 美化管理后台
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'django_filters',
    'user',
    'alert',
    'contact',
    'device',
    'file_management',
    'inventory',
    'repair',
    'integrated_facility',
    'operation_affairs',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 启用跨域请求
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'setting.urls'
# 启用跨域请求
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_CREDENTIALS = True  # 允许携带凭证
SIMPLEUI_CONFIG = {
    'system': {
        'keep': False,
        'name': '园区网网络管理系统',
        'icon': 'fas fa-chart-line',
    },
    'menus': [
        {
            'name': '用户管理',
            'icon': 'fas fa-users',
            'models': [
                {'name': '用户', 'icon': 'fas fa-user', 'url': 'user/user/'},

            ]
        },
        {
            'name': '数据审计',
            'icon': 'fas fa-chart-line',
            'models': [
                {'name': '联系人', 'icon': 'fas fa-address-book', 'url': 'contact/contact/'},
                {
                    'name': '设备管理',
                    'icon': 'fas fa-server',
                    'models': [
                        {'name': '网络设备', 'icon': 'fas fa-network-wired', 'url': 'device/networkdevice/'},
                        {'name': 'IP 地址管理', 'icon': 'fas fa-globe', 'url': 'device/ipam/'},
                        {'name': '终端信息', 'icon': 'fas fa-desktop', 'url': 'device/terminal/'},
                    ]
                }, {
                    'name': '基础设施',
                    'icon': 'fas fa-building',
                    'models': [
                        {'name': '机房', 'icon': 'fas fa-door-open', 'url': 'integrated_facility/equipmentrooms/'},
                        {'name': '机柜', 'icon': 'fas fa-archive', 'url': 'integrated_facility/rack/'},
                        {'name': '基础设施设备', 'icon': 'fas fa-fan',
                         'url': 'integrated_facility/infrastructureequipment/'},
                        {'name': '设备连接', 'icon': 'fas fa-link', 'url': 'integrated_facility/connection/'},
                    ]
                },
                {
                    'name': '库存管理',
                    'icon': 'fas fa-boxes',
                    'models': [
                        {'name': '库存物品', 'icon': 'fas fa-box', 'url': 'inventory/inventoryitem/'},
                        {'name': '出入库记录', 'icon': 'fas fa-dolly', 'url': 'inventory/inventoryrecord/'},
                    ]
                }, {
                    'name': '运维管理',
                    'icon': 'fas fa-tools',
                    'models': [
                        {'name': '巡检计划', 'icon': 'fas fa-clipboard-check', 'url': 'operation_affairs/patrolplan/'},
                        {'name': '计划任务', 'icon': 'fas fa-tasks', 'url': 'operation_affairs/patroltask/'},
                    ]
                }, {
                    'name': '故障报修',
                    'icon': 'fas fa-exclamation-triangle',
                    'models': [
                        {'name': '工单', 'icon': 'fas fa-file-alt', 'url': 'repair/workorder/'},
                        {'name': '工单处理记录', 'icon': 'fas fa-history', 'url': 'repair/workorderhandlelog/'},
                        {'name': '工单评价', 'icon': 'fas fa-star', 'url': 'repair/workorderevaluation/'},
                    ]
                }, {
                    'name': '告警管理',
                    'icon': 'fas fa-bell',
                    'models': [
                        {'name': '告警', 'icon': 'fas fa-exclamation-circle', 'url': 'alert/alert/'},
                        {'name': 'Webhook 接收器', 'icon': ' fas fa-plug', 'url': 'alert/webhookreceiver/'},
                    ]
                },
            ]
        },

    ]
}
# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False
# 去掉默认Logo或换成自己Logo链接

# 设置默认主题，指向主题css文件名。Element-ui风格
SIMPLEUI_DEFAULT_THEME = 'element.css'
# 自定义管理后台标题和 logo
SIMPLEUI_TITLE = '园区网网络管理系统'  # 管理后台标题
SIMPLEUI_LOGO = '/media/ipv4.png'  # Logo 图片 URL

# REST Framework 配置
# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#     ),
# }
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '[%(levelname)s] %(name)s: %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'debug.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5MB
            'backupCount': 3,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'operation_affairs': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
        },
    },
}
# JWT 配置
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=60),  # 访问令牌有效期
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365),  # 刷新令牌有效期
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'setting.wsgi.application'
# 媒体文件目录（用于用户上传的文件）
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# 按需切换成mysql
# from decouple import config
#
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': config('DB_NAME'),
#         'USER': config('DB_USER'),
#         'PASSWORD': config('DB_PASSWORD'),
#         'HOST': config('DB_HOST'),
#         'PORT': config('DB_PORT'),
#     }
# }
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
# 文件上传大小限制 (100GB = 107374182400 bytes)
DATA_UPLOAD_MAX_MEMORY_SIZE = 107374182400  # 100GB
FILE_UPLOAD_MAX_MEMORY_SIZE = 107374182400  # 100GB

# 其他相关设置
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'
#
# TIME_ZONE = 'UTC'
#
# USE_I18N = True
#
# USE_TZ = True
# 设置时区为上海
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False
DATETIME_FORMAT = 'Y-m-d H:i:s'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'user.User'  # 自定义用户类
