# Generated by Django 5.2.8 on 2026-03-13 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPAM',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='IP地址管理id')),
                ('ip_address', models.CharField(max_length=255, verbose_name='IP地址')),
                ('dhcp', models.CharField(max_length=255, verbose_name='DHCP')),
                ('reserved', models.CharField(max_length=255, verbose_name='保留')),
                ('vlan', models.CharField(max_length=4, verbose_name='VLAN接口')),
                ('business_system', models.CharField(max_length=255, verbose_name='承载业务')),
                ('remarks', models.TextField(null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=255, null=True, verbose_name='设备名称')),
                ('ip_address', models.GenericIPAddressField(help_text='管理IP地址（可为空，支持IPv4/IPv6）', null=True,
                                                            validators=[django.core.validators.RegexValidator(
                                                                message='请输入有效的 IPv4 地址，如 192.168.1.1',
                                                                regex='^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$')])),
                ('mac_address', models.CharField(help_text='MAC地址', max_length=17, null=True, validators=[
                    django.core.validators.RegexValidator(regex='^([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$')])),
                ('type', models.CharField(default='交换机', help_text='设备类型', max_length=64)),
                ('model', models.CharField(blank=True, help_text='设备型号', max_length=64, null=True)),
                ('sn', models.CharField(blank=True, help_text='序列号', max_length=64, null=True)),
                ('location',
                 models.CharField(blank=True, help_text='物理位置，如 3楼机房A排', max_length=255, null=True)),
                ('maintenance_start', models.DateField(blank=True, help_text='维保开始日期', null=True)),
                ('maintenance_end', models.DateField(blank=True, help_text='维保截止日期', null=True)),
                ('local_admin_name',
                 models.CharField(blank=True, help_text='本地管理员用户名', max_length=64, null=True)),
                ('local_admin_password',
                 models.CharField(blank=True, help_text='本地管理员密码（建议加密存储）', max_length=128, null=True)),
                ('system_info',
                 models.CharField(help_text='系统信息，如操作系统、版本、架构等', max_length=255, null=True)),
                ('login_protocol',
                 models.CharField(default='ssh', help_text='远程登录协议是telnet还是ssh', max_length=6, validators=[
                     django.core.validators.RegexValidator(message="登录协议必须是 'ssh' 或 'telnet'",
                                                           regex='^(ssh|telnet|http|https)$')])),
                ('login_username', models.CharField(blank=True, help_text='登录用户名', max_length=64, null=True)),
                ('login_password', models.CharField(blank=True, help_text='登录密码', max_length=128, null=True)),
                ('login_port', models.IntegerField(default=22, help_text='端口号')),
                ('is_active', models.BooleanField(default=True, help_text='是否在使用中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '网络设备',
                'verbose_name_plural': '网络设备',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='终端信息id')),
                ('name', models.CharField(max_length=255, verbose_name='终端名称')),
                ('ip_address', models.CharField(max_length=255, verbose_name='IP地址')),
                ('mac_address', models.CharField(max_length=255, verbose_name='MAC地址')),
                ('vlan', models.CharField(blank=True, max_length=255, null=True, verbose_name='VLAN')),
                ('remarks', models.TextField(null=True, verbose_name='备注')),
            ],
        ),
    ]
