# Generated by Django 5.2.8 on 2026-03-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipam',
            name='dhcp',
            field=models.CharField(max_length=255, verbose_name='DHCP地址段'),
        ),
        migrations.AlterField(
            model_name='ipam',
            name='ip_address',
            field=models.CharField(max_length=255, verbose_name='IP地址段'),
        ),
        migrations.AlterField(
            model_name='ipam',
            name='reserved',
            field=models.CharField(max_length=255, verbose_name='保留地址段'),
        ),
    ]
