# Generated by Django 5.2.8 on 2026-03-13 15:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='物品名称')),
                ('item_type', models.CharField(max_length=20, verbose_name='物品类型')),
                ('image', models.CharField(max_length=255, null=True, verbose_name='物品图片')),
                ('location', models.CharField(max_length=200, verbose_name='存放位置')),
                ('quantity', models.IntegerField(default=0, verbose_name='当前库存')),
                ('unit', models.CharField(max_length=20, verbose_name='单位')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '库存物品',
                'verbose_name_plural': '库存物品',
                'ordering': ['-created_at'],
            },
        ),
    ]
