# Generated by Django 5.2.8 on 2026-03-22 17:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_type',
                 models.CharField(choices=[('in', '入库'), ('out', '出库')], max_length=3, verbose_name='操作类型')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('operation_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('inventory_item',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem',
                                   verbose_name='物品')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL,
                                               verbose_name='操作人')),
            ],
            options={
                'verbose_name': '出入库记录',
                'verbose_name_plural': '出入库记录',
                'ordering': ['-operation_time'],
            },
        ),
    ]
