# Generated by Django 5.2.8 on 2026-03-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='other', max_length=50, verbose_name='告警来源')),
                ('severity', models.CharField(default='warning', max_length=20, verbose_name='告警级别')),
                ('status', models.CharField(default='未确认', max_length=20, verbose_name='告警状态')),
                ('title', models.CharField(default='snmp告警', max_length=200, verbose_name='告警标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='告警详情')),
                ('host', models.CharField(blank=True, max_length=100, null=True, verbose_name='主机名')),
                ('ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='IP地址')),
                ('raw_data', models.JSONField(blank=True, default=dict, null=True, verbose_name='原始数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('confirm_at', models.DateTimeField(auto_now_add=True, verbose_name='确认时间')),
            ],
            options={
                'db_table': 'alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('source', models.CharField(default='zabbix', max_length=50, verbose_name='来源平台')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('api_token', models.CharField(max_length=200, verbose_name='密钥令牌')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Webhook接收器',
                'verbose_name_plural': 'Webhook接收器',
                'db_table': 'webhook_receivers',
                'ordering': ['-updated_at'],
            },
        ),
    ]
