# Generated by Django 5.2.8 on 2026-03-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatrolPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=100, verbose_name='巡检计划名称')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('publisher', models.CharField(max_length=100, verbose_name='发布人')),
                ('executor', models.CharField(max_length=100, verbose_name='执行人')),
                ('patrol_content', models.TextField(verbose_name='巡检内容')),
                ('output_content', models.TextField(verbose_name='巡检输出内容')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '巡检计划',
                'verbose_name_plural': '巡检计划',
            },
        ),
        migrations.CreateModel(
            name='PatrolTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100, verbose_name='计划任务名称')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('publisher', models.CharField(max_length=100, verbose_name='发布人')),
                ('executor', models.CharField(max_length=100, verbose_name='执行人')),
                ('task_content', models.TextField(verbose_name='任务内容')),
                ('task_target', models.TextField(verbose_name='任务目标')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '巡检任务',
                'verbose_name_plural': '巡检任务',
            },
        ),
    ]
