# Generated by Django 5.2.8 on 2026-03-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('integrated_facility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rack',
            name='equipment_room_id',
            field=models.BigIntegerField(default=0, verbose_name='所属设备间id'),
        ),
    ]
